---
name: Publish MkDocs

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish_mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rye
        run: |
          curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: Install Python & MkDocs & Plugins
        run: rye sync

      - name: Publish document
        run: rye run mkdocs gh-deploy --force
